version: '3'
services:
        haus-server:
                build:
                        context: .
                        dockerfile: Dockerfile
                image: haus-server
                container_name: haus-server
                restart: unless-stopped
                environment:
                        - PORT=8080
                        - NODE_ENV=production
                command: yarn start
                volumes:
                        - .:/usr/app
                ports:
                        - 8080:8080
